export const XLM_ADDRESS = 'CB64D3G7SM2RTH6JSGG34DDTFTQ5CFDKVDZJZSODMCX4NJ2HV2KN7OHT'

const UNDERLYING_XLM_ADDRESS = 'CD4UEK2CF6LEVAIMYRH7DOEN2AP3CKO763UO2HGBXHVCS5DIFTRKIIBM'
const UNDERLYING_XRP_ADDRESS = 'CAF2Z5L5INKVZBIQ3CDDAAHUNQOUS6NSYBUI6ZLK2DSHXBZ3I23HM6Q7'
const UNDERLYING_USDC_ADDRESS = 'CDZI6HFGUFB7XJWXLOWW6MUQQ6YX3NPA36ADTYNMRRX7H5YG7GK7I7SU'
const S_TOKEN_XLM = 'CAC2ASEKVFU4YH5HIY3OUG2D2KSEUMFEZ36R2LHM53HMEISGWNXEBVW7'
const S_TOKEN_XRP = 'CC4UUAVB66BT4XATZY5YJIGLEYS4ADVRIIYMTAQ4HBMMO3YYC2ASRHEC'
const S_TOKEN_USDC = 'CC2M4S57Y6QH3EEE4JXIL4LZHJ7EN57KBXWGMKDCZRH4HT5ROXX5U7VK'

export const SUPPORTED_TOKENS = ['usdc', 'xlm', 'xrp'] as const

export type SupportedToken = (typeof SUPPORTED_TOKENS)[number]

export interface Token {
  code: string
  title: string
  address: string
  sAddress: string
}

export const tokens: Record<SupportedToken, Token> = {
  xlm: {
    code: 'XLM',
    title: 'Lumen',
    address: UNDERLYING_XLM_ADDRESS,
    sAddress: S_TOKEN_XLM,
  },
  xrp: {
    code: 'XRP',
    title: 'Ripple',
    address: UNDERLYING_XRP_ADDRESS,
    sAddress: S_TOKEN_XRP,
  },
  usdc: {
    code: 'USDC',
    title: 'USD Coin',
    address: UNDERLYING_USDC_ADDRESS,
    sAddress: S_TOKEN_USDC,
  },
}
