name: TESTS
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Use Node.js 18.17.1
          uses: actions/setup-node@v3
          with:
            node-version: 18.17.1
        - name: Build for testing
          run: |
            yarn
            yarn test

    test-build-image:
      runs-on: ubuntu-latest
      strategy:
            matrix:
              apps: [app, landing]
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build image ${{ matrix.apps }} 
          uses: docker/build-push-action@v4
          with:
            build-args: |
              BUILD_CONTEXT=${{ matrix.apps }} 
              NEXT_PUBLIC_BUILD_NUMBER_ARG=${{ github.sha }}
            context: .
            push: false