name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            apps: [app, landing]
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Use Node.js 18.17.1
          uses: actions/setup-node@v3
          with:
            node-version: 18.17.1
        - name: Build for testing
          run: |
            yarn
            yarn test
        - name: Tyest build ${{ matrix.apps }}
          run: |
            yarn workspace @slender/${{ matrix.apps }} build

